package evidence

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"flightlab/internal/scenario"
)

// Save stores the evidence generated by one FlightLab execution.
func Save(baseDir string, result scenario.Result) (string, error) {
	if result.ID == "" {
		return "", fmt.Errorf("result has no run ID")
	}

	runDir := filepath.Join(
		baseDir,
		result.ID,
	)

	// Create the evidence directory before saving any files into it.
	if err := os.MkdirAll(
		runDir,
		0755,
	); err != nil {
		return "", fmt.Errorf(
			"failed to create evidence directory: %w",
			err,
		)
	}

	// If a custom C2 library was used, save a copy
	// inside the evidence directory.
	if result.Config.C2Library != "" {
		c2Destination := filepath.Join(
			runDir,
			"c2-targets.txt",
		)

		if err := copyFile(
			result.Config.C2Library,
			c2Destination,
		); err != nil {
			return "", fmt.Errorf(
				"failed to save C2 target library: %w",
				err,
			)
		}

		// Store the relative evidence path in result.json.
		result.C2LibraryPath = "c2-targets.txt"
	}

	// If packet capture was enabled, copy the temporary PCAP
	// into the evidence directory.
	if result.CaptureTempPath != "" {
		finalCapturePath := filepath.Join(
			runDir,
			"capture.pcap",
		)

		if err := copyFile(
			result.CaptureTempPath,
			finalCapturePath,
		); err != nil {
			return "", fmt.Errorf(
				"failed to save packet capture: %w",
				err,
			)
		}

		// Remove the temporary capture after it has been copied.
		_ = os.Remove(
			result.CaptureTempPath,
		)

		// Store the relative evidence path in result.json.
		result.CapturePath = "capture.pcap"
	}

	// If Suricata output was generated, copy the temporary EVE JSON
	// into the evidence directory.
	if result.SuricataTempPath != "" {
		finalSuricataPath := filepath.Join(
			runDir,
			"suricata-eve.json",
		)

		if err := copyFile(
			result.SuricataTempPath,
			finalSuricataPath,
		); err != nil {
			return "", fmt.Errorf(
				"failed to save Suricata EVE output: %w",
				err,
			)
		}

		// Store the relative evidence path in result.json.
		result.SuricataPath = "suricata-eve.json"

		// Remove the temporary Suricata directory after
		// the EVE output has been copied.
		if result.SuricataTempDir != "" {
			_ = os.RemoveAll(
				result.SuricataTempDir,
			)
		}
	}

	// Save the complete structured result.
	// This happens after all evidence paths have been updated
	// so result.json contains the final relative paths.
	jsonData, err := json.MarshalIndent(
		result,
		"",
		"  ",
	)
	if err != nil {
		return "", fmt.Errorf(
			"failed to encode result JSON: %w",
			err,
		)
	}

	resultPath := filepath.Join(
		runDir,
		"result.json",
	)

	if err := os.WriteFile(
		resultPath,
		jsonData,
		0644,
	); err != nil {
		return "", fmt.Errorf(
			"failed to save result JSON: %w",
			err,
		)
	}

	// Save the original FlightSim terminal output separately.
	outputPath := filepath.Join(
		runDir,
		"flightsim-output.txt",
	)

	if err := os.WriteFile(
		outputPath,
		[]byte(result.Output),
		0644,
	); err != nil {
		return "", fmt.Errorf(
			"failed to save FlightSim output: %w",
			err,
		)
	}

	return runDir, nil
}

// copyFile copies a file from source to destination.
func copyFile(
	source string,
	destination string,
) error {

	src, err := os.Open(source)
	if err != nil {
		return err
	}
	defer src.Close()

	dst, err := os.Create(destination)
	if err != nil {
		return err
	}
	defer dst.Close()

	_, err = io.Copy(
		dst,
		src,
	)

	return err
}
